FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
        build-essential \
        libcriterion-dev \
        pkg-config \
        file \
        gdb \
        valgrind \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

