name: CI (bool)

on:
  push:
    branches: [ master ]
    paths:
      - 'ngutils/bool/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'ngutils/bool/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcriterion-dev pkg-config

      - name: Build and run tests
        working-directory: ngutils/bool   # ← вот сюда
        run: make test

